/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/album_artists": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.album_artists.id"];
          artist?: parameters["rowFilter.album_artists.artist"];
          album?: parameters["rowFilter.album_artists.album"];
          position?: parameters["rowFilter.album_artists.position"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["album_artists"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** album_artists */
          album_artists?: definitions["album_artists"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.album_artists.id"];
          artist?: parameters["rowFilter.album_artists.artist"];
          album?: parameters["rowFilter.album_artists.album"];
          position?: parameters["rowFilter.album_artists.position"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.album_artists.id"];
          artist?: parameters["rowFilter.album_artists.artist"];
          album?: parameters["rowFilter.album_artists.album"];
          position?: parameters["rowFilter.album_artists.position"];
        };
        body: {
          /** album_artists */
          album_artists?: definitions["album_artists"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/album_links": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.album_links.id"];
          href?: parameters["rowFilter.album_links.href"];
          artwork?: parameters["rowFilter.album_links.artwork"];
          last_checked_at?: parameters["rowFilter.album_links.last_checked_at"];
          album?: parameters["rowFilter.album_links.album"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["album_links"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** album_links */
          album_links?: definitions["album_links"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.album_links.id"];
          href?: parameters["rowFilter.album_links.href"];
          artwork?: parameters["rowFilter.album_links.artwork"];
          last_checked_at?: parameters["rowFilter.album_links.last_checked_at"];
          album?: parameters["rowFilter.album_links.album"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.album_links.id"];
          href?: parameters["rowFilter.album_links.href"];
          artwork?: parameters["rowFilter.album_links.artwork"];
          last_checked_at?: parameters["rowFilter.album_links.last_checked_at"];
          album?: parameters["rowFilter.album_links.album"];
        };
        body: {
          /** album_links */
          album_links?: definitions["album_links"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/albums": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.albums.id"];
          title?: parameters["rowFilter.albums.title"];
          slug?: parameters["rowFilter.albums.slug"];
          artwork?: parameters["rowFilter.albums.artwork"];
          published_at?: parameters["rowFilter.albums.published_at"];
          artist?: parameters["rowFilter.albums.artist"];
          catalogNumber?: parameters["rowFilter.albums.catalogNumber"];
          links?: parameters["rowFilter.albums.links"];
          content?: parameters["rowFilter.albums.content"];
          tags?: parameters["rowFilter.albums.tags"];
          state?: parameters["rowFilter.albums.state"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["albums"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** albums */
          albums?: definitions["albums"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.albums.id"];
          title?: parameters["rowFilter.albums.title"];
          slug?: parameters["rowFilter.albums.slug"];
          artwork?: parameters["rowFilter.albums.artwork"];
          published_at?: parameters["rowFilter.albums.published_at"];
          artist?: parameters["rowFilter.albums.artist"];
          catalogNumber?: parameters["rowFilter.albums.catalogNumber"];
          links?: parameters["rowFilter.albums.links"];
          content?: parameters["rowFilter.albums.content"];
          tags?: parameters["rowFilter.albums.tags"];
          state?: parameters["rowFilter.albums.state"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.albums.id"];
          title?: parameters["rowFilter.albums.title"];
          slug?: parameters["rowFilter.albums.slug"];
          artwork?: parameters["rowFilter.albums.artwork"];
          published_at?: parameters["rowFilter.albums.published_at"];
          artist?: parameters["rowFilter.albums.artist"];
          catalogNumber?: parameters["rowFilter.albums.catalogNumber"];
          links?: parameters["rowFilter.albums.links"];
          content?: parameters["rowFilter.albums.content"];
          tags?: parameters["rowFilter.albums.tags"];
          state?: parameters["rowFilter.albums.state"];
        };
        body: {
          /** albums */
          albums?: definitions["albums"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/artist_links": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.artist_links.id"];
          platform?: parameters["rowFilter.artist_links.platform"];
          href?: parameters["rowFilter.artist_links.href"];
          artwork?: parameters["rowFilter.artist_links.artwork"];
          last_checked_at?: parameters["rowFilter.artist_links.last_checked_at"];
          artist?: parameters["rowFilter.artist_links.artist"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["artist_links"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** artist_links */
          artist_links?: definitions["artist_links"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.artist_links.id"];
          platform?: parameters["rowFilter.artist_links.platform"];
          href?: parameters["rowFilter.artist_links.href"];
          artwork?: parameters["rowFilter.artist_links.artwork"];
          last_checked_at?: parameters["rowFilter.artist_links.last_checked_at"];
          artist?: parameters["rowFilter.artist_links.artist"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.artist_links.id"];
          platform?: parameters["rowFilter.artist_links.platform"];
          href?: parameters["rowFilter.artist_links.href"];
          artwork?: parameters["rowFilter.artist_links.artwork"];
          last_checked_at?: parameters["rowFilter.artist_links.last_checked_at"];
          artist?: parameters["rowFilter.artist_links.artist"];
        };
        body: {
          /** artist_links */
          artist_links?: definitions["artist_links"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/artists": {
    get: {
      parameters: {
        query: {
          title?: parameters["rowFilter.artists.title"];
          slug?: parameters["rowFilter.artists.slug"];
          links?: parameters["rowFilter.artists.links"];
          artwork?: parameters["rowFilter.artists.artwork"];
          id?: parameters["rowFilter.artists.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["artists"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** artists */
          artists?: definitions["artists"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          title?: parameters["rowFilter.artists.title"];
          slug?: parameters["rowFilter.artists.slug"];
          links?: parameters["rowFilter.artists.links"];
          artwork?: parameters["rowFilter.artists.artwork"];
          id?: parameters["rowFilter.artists.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          title?: parameters["rowFilter.artists.title"];
          slug?: parameters["rowFilter.artists.slug"];
          links?: parameters["rowFilter.artists.links"];
          artwork?: parameters["rowFilter.artists.artwork"];
          id?: parameters["rowFilter.artists.id"];
        };
        body: {
          /** artists */
          artists?: definitions["artists"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/chapters": {
    get: {
      parameters: {
        query: {
          title?: parameters["rowFilter.chapters.title"];
          slug?: parameters["rowFilter.chapters.slug"];
          position?: parameters["rowFilter.chapters.position"];
          links?: parameters["rowFilter.chapters.links"];
          artwork?: parameters["rowFilter.chapters.artwork"];
          id?: parameters["rowFilter.chapters.id"];
          show?: parameters["rowFilter.chapters.show"];
          /** any social media associated to the DJ / performer */
          socials?: parameters["rowFilter.chapters.socials"];
          state?: parameters["rowFilter.chapters.state"];
          content?: parameters["rowFilter.chapters.content"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["chapters"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** chapters */
          chapters?: definitions["chapters"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          title?: parameters["rowFilter.chapters.title"];
          slug?: parameters["rowFilter.chapters.slug"];
          position?: parameters["rowFilter.chapters.position"];
          links?: parameters["rowFilter.chapters.links"];
          artwork?: parameters["rowFilter.chapters.artwork"];
          id?: parameters["rowFilter.chapters.id"];
          show?: parameters["rowFilter.chapters.show"];
          /** any social media associated to the DJ / performer */
          socials?: parameters["rowFilter.chapters.socials"];
          state?: parameters["rowFilter.chapters.state"];
          content?: parameters["rowFilter.chapters.content"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          title?: parameters["rowFilter.chapters.title"];
          slug?: parameters["rowFilter.chapters.slug"];
          position?: parameters["rowFilter.chapters.position"];
          links?: parameters["rowFilter.chapters.links"];
          artwork?: parameters["rowFilter.chapters.artwork"];
          id?: parameters["rowFilter.chapters.id"];
          show?: parameters["rowFilter.chapters.show"];
          /** any social media associated to the DJ / performer */
          socials?: parameters["rowFilter.chapters.socials"];
          state?: parameters["rowFilter.chapters.state"];
          content?: parameters["rowFilter.chapters.content"];
        };
        body: {
          /** chapters */
          chapters?: definitions["chapters"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/events": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          title?: parameters["rowFilter.events.title"];
          artwork?: parameters["rowFilter.events.artwork"];
          published_at?: parameters["rowFilter.events.published_at"];
          links?: parameters["rowFilter.events.links"];
          event_type?: parameters["rowFilter.events.event_type"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["events"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** events */
          events?: definitions["events"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          title?: parameters["rowFilter.events.title"];
          artwork?: parameters["rowFilter.events.artwork"];
          published_at?: parameters["rowFilter.events.published_at"];
          links?: parameters["rowFilter.events.links"];
          event_type?: parameters["rowFilter.events.event_type"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          title?: parameters["rowFilter.events.title"];
          artwork?: parameters["rowFilter.events.artwork"];
          published_at?: parameters["rowFilter.events.published_at"];
          links?: parameters["rowFilter.events.links"];
          event_type?: parameters["rowFilter.events.event_type"];
        };
        body: {
          /** events */
          events?: definitions["events"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/links": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.links.id"];
          platform?: parameters["rowFilter.links.platform"];
          href?: parameters["rowFilter.links.href"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["links"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** links */
          links?: definitions["links"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.links.id"];
          platform?: parameters["rowFilter.links.platform"];
          href?: parameters["rowFilter.links.href"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.links.id"];
          platform?: parameters["rowFilter.links.platform"];
          href?: parameters["rowFilter.links.href"];
        };
        body: {
          /** links */
          links?: definitions["links"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/markers": {
    get: {
      parameters: {
        query: {
          timestamp?: parameters["rowFilter.markers.timestamp"];
          /** Artist and Title of track */
          rawTrack?: parameters["rowFilter.markers.rawTrack"];
          position?: parameters["rowFilter.markers.position"];
          track?: parameters["rowFilter.markers.track"];
          id?: parameters["rowFilter.markers.id"];
          chapter?: parameters["rowFilter.markers.chapter"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["markers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** markers */
          markers?: definitions["markers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          timestamp?: parameters["rowFilter.markers.timestamp"];
          /** Artist and Title of track */
          rawTrack?: parameters["rowFilter.markers.rawTrack"];
          position?: parameters["rowFilter.markers.position"];
          track?: parameters["rowFilter.markers.track"];
          id?: parameters["rowFilter.markers.id"];
          chapter?: parameters["rowFilter.markers.chapter"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          timestamp?: parameters["rowFilter.markers.timestamp"];
          /** Artist and Title of track */
          rawTrack?: parameters["rowFilter.markers.rawTrack"];
          position?: parameters["rowFilter.markers.position"];
          track?: parameters["rowFilter.markers.track"];
          id?: parameters["rowFilter.markers.id"];
          chapter?: parameters["rowFilter.markers.chapter"];
        };
        body: {
          /** markers */
          markers?: definitions["markers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/posts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          title?: parameters["rowFilter.posts.title"];
          published_at?: parameters["rowFilter.posts.published_at"];
          state?: parameters["rowFilter.posts.state"];
          href?: parameters["rowFilter.posts.href"];
          artwork?: parameters["rowFilter.posts.artwork"];
          profile?: parameters["rowFilter.posts.profile"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["posts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** posts */
          posts?: definitions["posts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          title?: parameters["rowFilter.posts.title"];
          published_at?: parameters["rowFilter.posts.published_at"];
          state?: parameters["rowFilter.posts.state"];
          href?: parameters["rowFilter.posts.href"];
          artwork?: parameters["rowFilter.posts.artwork"];
          profile?: parameters["rowFilter.posts.profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          title?: parameters["rowFilter.posts.title"];
          published_at?: parameters["rowFilter.posts.published_at"];
          state?: parameters["rowFilter.posts.state"];
          href?: parameters["rowFilter.posts.href"];
          artwork?: parameters["rowFilter.posts.artwork"];
          profile?: parameters["rowFilter.posts.profile"];
        };
        body: {
          /** posts */
          posts?: definitions["posts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.profiles.slug"];
          title?: parameters["rowFilter.profiles.title"];
          published_at?: parameters["rowFilter.profiles.published_at"];
          created_by?: parameters["rowFilter.profiles.created_by"];
          updated_by?: parameters["rowFilter.profiles.updated_by"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          id?: parameters["rowFilter.profiles.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.profiles.slug"];
          title?: parameters["rowFilter.profiles.title"];
          published_at?: parameters["rowFilter.profiles.published_at"];
          created_by?: parameters["rowFilter.profiles.created_by"];
          updated_by?: parameters["rowFilter.profiles.updated_by"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          id?: parameters["rowFilter.profiles.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.profiles.slug"];
          title?: parameters["rowFilter.profiles.title"];
          published_at?: parameters["rowFilter.profiles.published_at"];
          created_by?: parameters["rowFilter.profiles.created_by"];
          updated_by?: parameters["rowFilter.profiles.updated_by"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          id?: parameters["rowFilter.profiles.id"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/shows": {
    get: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.shows.slug"];
          title?: parameters["rowFilter.shows.title"];
          state?: parameters["rowFilter.shows.state"];
          /** path or URL to artwork */
          artwork?: parameters["rowFilter.shows.artwork"];
          duration?: parameters["rowFilter.shows.duration"];
          published_at?: parameters["rowFilter.shows.published_at"];
          links?: parameters["rowFilter.shows.links"];
          content?: parameters["rowFilter.shows.content"];
          tags?: parameters["rowFilter.shows.tags"];
          location?: parameters["rowFilter.shows.location"];
          id?: parameters["rowFilter.shows.id"];
          profile?: parameters["rowFilter.shows.profile"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["shows"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** shows */
          shows?: definitions["shows"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.shows.slug"];
          title?: parameters["rowFilter.shows.title"];
          state?: parameters["rowFilter.shows.state"];
          /** path or URL to artwork */
          artwork?: parameters["rowFilter.shows.artwork"];
          duration?: parameters["rowFilter.shows.duration"];
          published_at?: parameters["rowFilter.shows.published_at"];
          links?: parameters["rowFilter.shows.links"];
          content?: parameters["rowFilter.shows.content"];
          tags?: parameters["rowFilter.shows.tags"];
          location?: parameters["rowFilter.shows.location"];
          id?: parameters["rowFilter.shows.id"];
          profile?: parameters["rowFilter.shows.profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.shows.slug"];
          title?: parameters["rowFilter.shows.title"];
          state?: parameters["rowFilter.shows.state"];
          /** path or URL to artwork */
          artwork?: parameters["rowFilter.shows.artwork"];
          duration?: parameters["rowFilter.shows.duration"];
          published_at?: parameters["rowFilter.shows.published_at"];
          links?: parameters["rowFilter.shows.links"];
          content?: parameters["rowFilter.shows.content"];
          tags?: parameters["rowFilter.shows.tags"];
          location?: parameters["rowFilter.shows.location"];
          id?: parameters["rowFilter.shows.id"];
          profile?: parameters["rowFilter.shows.profile"];
        };
        body: {
          /** shows */
          shows?: definitions["shows"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/shows_duplicate": {
    get: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.shows_duplicate.slug"];
          title?: parameters["rowFilter.shows_duplicate.title"];
          state?: parameters["rowFilter.shows_duplicate.state"];
          artwork?: parameters["rowFilter.shows_duplicate.artwork"];
          duration?: parameters["rowFilter.shows_duplicate.duration"];
          published_at?: parameters["rowFilter.shows_duplicate.published_at"];
          links?: parameters["rowFilter.shows_duplicate.links"];
          content?: parameters["rowFilter.shows_duplicate.content"];
          tags?: parameters["rowFilter.shows_duplicate.tags"];
          location?: parameters["rowFilter.shows_duplicate.location"];
          id?: parameters["rowFilter.shows_duplicate.id"];
          profile?: parameters["rowFilter.shows_duplicate.profile"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["shows_duplicate"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** shows_duplicate */
          shows_duplicate?: definitions["shows_duplicate"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.shows_duplicate.slug"];
          title?: parameters["rowFilter.shows_duplicate.title"];
          state?: parameters["rowFilter.shows_duplicate.state"];
          artwork?: parameters["rowFilter.shows_duplicate.artwork"];
          duration?: parameters["rowFilter.shows_duplicate.duration"];
          published_at?: parameters["rowFilter.shows_duplicate.published_at"];
          links?: parameters["rowFilter.shows_duplicate.links"];
          content?: parameters["rowFilter.shows_duplicate.content"];
          tags?: parameters["rowFilter.shows_duplicate.tags"];
          location?: parameters["rowFilter.shows_duplicate.location"];
          id?: parameters["rowFilter.shows_duplicate.id"];
          profile?: parameters["rowFilter.shows_duplicate.profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          slug?: parameters["rowFilter.shows_duplicate.slug"];
          title?: parameters["rowFilter.shows_duplicate.title"];
          state?: parameters["rowFilter.shows_duplicate.state"];
          artwork?: parameters["rowFilter.shows_duplicate.artwork"];
          duration?: parameters["rowFilter.shows_duplicate.duration"];
          published_at?: parameters["rowFilter.shows_duplicate.published_at"];
          links?: parameters["rowFilter.shows_duplicate.links"];
          content?: parameters["rowFilter.shows_duplicate.content"];
          tags?: parameters["rowFilter.shows_duplicate.tags"];
          location?: parameters["rowFilter.shows_duplicate.location"];
          id?: parameters["rowFilter.shows_duplicate.id"];
          profile?: parameters["rowFilter.shows_duplicate.profile"];
        };
        body: {
          /** shows_duplicate */
          shows_duplicate?: definitions["shows_duplicate"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/supply": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.supply.id"];
          title?: parameters["rowFilter.supply.title"];
          artwork?: parameters["rowFilter.supply.artwork"];
          published_at?: parameters["rowFilter.supply.published_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["supply"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** supply */
          supply?: definitions["supply"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.supply.id"];
          title?: parameters["rowFilter.supply.title"];
          artwork?: parameters["rowFilter.supply.artwork"];
          published_at?: parameters["rowFilter.supply.published_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.supply.id"];
          title?: parameters["rowFilter.supply.title"];
          artwork?: parameters["rowFilter.supply.artwork"];
          published_at?: parameters["rowFilter.supply.published_at"];
        };
        body: {
          /** supply */
          supply?: definitions["supply"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/tags": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          name?: parameters["rowFilter.tags.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tags */
          tags?: definitions["tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          name?: parameters["rowFilter.tags.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          name?: parameters["rowFilter.tags.name"];
        };
        body: {
          /** tags */
          tags?: definitions["tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/track_links": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.track_links.id"];
          platform?: parameters["rowFilter.track_links.platform"];
          href?: parameters["rowFilter.track_links.href"];
          artwork?: parameters["rowFilter.track_links.artwork"];
          last_checked_at?: parameters["rowFilter.track_links.last_checked_at"];
          track?: parameters["rowFilter.track_links.track"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["track_links"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** track_links */
          track_links?: definitions["track_links"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.track_links.id"];
          platform?: parameters["rowFilter.track_links.platform"];
          href?: parameters["rowFilter.track_links.href"];
          artwork?: parameters["rowFilter.track_links.artwork"];
          last_checked_at?: parameters["rowFilter.track_links.last_checked_at"];
          track?: parameters["rowFilter.track_links.track"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.track_links.id"];
          platform?: parameters["rowFilter.track_links.platform"];
          href?: parameters["rowFilter.track_links.href"];
          artwork?: parameters["rowFilter.track_links.artwork"];
          last_checked_at?: parameters["rowFilter.track_links.last_checked_at"];
          track?: parameters["rowFilter.track_links.track"];
        };
        body: {
          /** track_links */
          track_links?: definitions["track_links"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/tracks": {
    get: {
      parameters: {
        query: {
          title?: parameters["rowFilter.tracks.title"];
          slug?: parameters["rowFilter.tracks.slug"];
          path?: parameters["rowFilter.tracks.path"];
          artwork?: parameters["rowFilter.tracks.artwork"];
          artist?: parameters["rowFilter.tracks.artist"];
          id?: parameters["rowFilter.tracks.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tracks"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tracks */
          tracks?: definitions["tracks"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          title?: parameters["rowFilter.tracks.title"];
          slug?: parameters["rowFilter.tracks.slug"];
          path?: parameters["rowFilter.tracks.path"];
          artwork?: parameters["rowFilter.tracks.artwork"];
          artist?: parameters["rowFilter.tracks.artist"];
          id?: parameters["rowFilter.tracks.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          title?: parameters["rowFilter.tracks.title"];
          slug?: parameters["rowFilter.tracks.slug"];
          path?: parameters["rowFilter.tracks.path"];
          artwork?: parameters["rowFilter.tracks.artwork"];
          artist?: parameters["rowFilter.tracks.artist"];
          id?: parameters["rowFilter.tracks.id"];
        };
        body: {
          /** tracks */
          tracks?: definitions["tracks"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/tags_counts": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/search_tracks": {
    post: {
      parameters: {
        body: {
          args: {
            query: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/site_search": {
    post: {
      parameters: {
        body: {
          args: {
            query: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/shortkey_generate": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/set_album_slug_from_name": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/search_artists": {
    post: {
      parameters: {
        body: {
          args: {
            query: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/slugify": {
    post: {
      parameters: {
        body: {
          args: {
            value: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/unaccent_lexize": {
    post: {
      parameters: {
        body: {
          args: {
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/unaccent": {
    post: {
      parameters: {
        body: {
          args: {
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/unaccent_init": {
    post: {
      parameters: {
        body: {
          args: {
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/notify_api_restart": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_duplicate_artists": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  album_artists: {
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `artists.id`.<fk table='artists' column='id'/>
     */
    artist: string;
    /**
     * Note:
     * This is a Foreign Key to `albums.id`.<fk table='albums' column='id'/>
     */
    album: string;
    position: number;
  };
  album_links: {
    id: string;
    href?: string;
    artwork?: string;
    last_checked_at: string;
    /**
     * Note:
     * This is a Foreign Key to `albums.id`.<fk table='albums' column='id'/>
     */
    album: string;
  };
  albums: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    title: string;
    slug: string;
    artwork?: string;
    published_at: string;
    /**
     * Note:
     * This is a Foreign Key to `artists.id`.<fk table='artists' column='id'/>
     */
    artist?: string;
    catalogNumber?: string;
    links?: string;
    content?: string;
    tags?: string;
    state: string;
  };
  /** This is a duplicate copy of track_links */
  artist_links: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    platform?: string;
    href?: string;
    artwork?: string;
    last_checked_at?: string;
    artist?: string;
  };
  artists: {
    title: string;
    slug: string;
    links?: string;
    artwork?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
  chapters: {
    title: string;
    slug: string;
    position: number;
    links?: string;
    artwork?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `shows.id`.<fk table='shows' column='id'/>
     */
    show?: string;
    /** any social media associated to the DJ / performer */
    socials?: string;
    state: string;
    content?: string;
  };
  events: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    title?: string;
    artwork?: string;
    published_at: string;
    links?: string;
    event_type?: string;
  };
  links: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    platform: string;
    href: string;
  };
  markers: {
    timestamp?: string;
    /** Artist and Title of track */
    rawTrack?: string;
    position: number;
    /**
     * Note:
     * This is a Foreign Key to `tracks.id`.<fk table='tracks' column='id'/>
     */
    track?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `chapters.id`.<fk table='chapters' column='id'/>
     */
    chapter: string;
  };
  posts: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    title: string;
    published_at: string;
    state: string;
    href?: string;
    artwork?: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    profile: string;
  };
  profiles: {
    slug?: string;
    title?: string;
    published_at?: string;
    created_by?: number;
    updated_by?: number;
    created_at?: string;
    updated_at?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
  shows: {
    slug: string;
    title: string;
    state: string;
    /** path or URL to artwork */
    artwork?: string;
    duration: number;
    published_at?: string;
    links?: {
      appleMusic: string;
      soundcloud: string;
    };
    content?: string;
    tags?: string;
    location?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    profile: string;
  };
  /** This is a duplicate copy of shows */
  shows_duplicate: {
    slug?: string;
    title?: string;
    state?: string;
    artwork?: string;
    duration?: number;
    published_at?: string;
    links?: string;
    content?: string;
    tags?: string;
    location?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    profile?: string;
  };
  supply: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    title: string;
    artwork: string;
    published_at: string;
  };
  tags: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    name: string;
  };
  track_links: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    platform: string;
    href: string;
    artwork?: string;
    last_checked_at: string;
    /**
     * Note:
     * This is a Foreign Key to `tracks.id`.<fk table='tracks' column='id'/>
     */
    track?: string;
  };
  tracks: {
    title: string;
    slug: string;
    path: string;
    artwork?: string;
    /**
     * Note:
     * This is a Foreign Key to `artists.id`.<fk table='artists' column='id'/>
     */
    artist: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** album_artists */
  "body.album_artists": definitions["album_artists"];
  "rowFilter.album_artists.id": string;
  "rowFilter.album_artists.artist": string;
  "rowFilter.album_artists.album": string;
  "rowFilter.album_artists.position": string;
  /** album_links */
  "body.album_links": definitions["album_links"];
  "rowFilter.album_links.id": string;
  "rowFilter.album_links.href": string;
  "rowFilter.album_links.artwork": string;
  "rowFilter.album_links.last_checked_at": string;
  "rowFilter.album_links.album": string;
  /** albums */
  "body.albums": definitions["albums"];
  "rowFilter.albums.id": string;
  "rowFilter.albums.title": string;
  "rowFilter.albums.slug": string;
  "rowFilter.albums.artwork": string;
  "rowFilter.albums.published_at": string;
  "rowFilter.albums.artist": string;
  "rowFilter.albums.catalogNumber": string;
  "rowFilter.albums.links": string;
  "rowFilter.albums.content": string;
  "rowFilter.albums.tags": string;
  "rowFilter.albums.state": string;
  /** artist_links */
  "body.artist_links": definitions["artist_links"];
  "rowFilter.artist_links.id": string;
  "rowFilter.artist_links.platform": string;
  "rowFilter.artist_links.href": string;
  "rowFilter.artist_links.artwork": string;
  "rowFilter.artist_links.last_checked_at": string;
  "rowFilter.artist_links.artist": string;
  /** artists */
  "body.artists": definitions["artists"];
  "rowFilter.artists.title": string;
  "rowFilter.artists.slug": string;
  "rowFilter.artists.links": string;
  "rowFilter.artists.artwork": string;
  "rowFilter.artists.id": string;
  /** chapters */
  "body.chapters": definitions["chapters"];
  "rowFilter.chapters.title": string;
  "rowFilter.chapters.slug": string;
  "rowFilter.chapters.position": string;
  "rowFilter.chapters.links": string;
  "rowFilter.chapters.artwork": string;
  "rowFilter.chapters.id": string;
  "rowFilter.chapters.show": string;
  /** any social media associated to the DJ / performer */
  "rowFilter.chapters.socials": string;
  "rowFilter.chapters.state": string;
  "rowFilter.chapters.content": string;
  /** events */
  "body.events": definitions["events"];
  "rowFilter.events.id": string;
  "rowFilter.events.title": string;
  "rowFilter.events.artwork": string;
  "rowFilter.events.published_at": string;
  "rowFilter.events.links": string;
  "rowFilter.events.event_type": string;
  /** links */
  "body.links": definitions["links"];
  "rowFilter.links.id": string;
  "rowFilter.links.platform": string;
  "rowFilter.links.href": string;
  /** markers */
  "body.markers": definitions["markers"];
  "rowFilter.markers.timestamp": string;
  /** Artist and Title of track */
  "rowFilter.markers.rawTrack": string;
  "rowFilter.markers.position": string;
  "rowFilter.markers.track": string;
  "rowFilter.markers.id": string;
  "rowFilter.markers.chapter": string;
  /** posts */
  "body.posts": definitions["posts"];
  "rowFilter.posts.id": string;
  "rowFilter.posts.title": string;
  "rowFilter.posts.published_at": string;
  "rowFilter.posts.state": string;
  "rowFilter.posts.href": string;
  "rowFilter.posts.artwork": string;
  "rowFilter.posts.profile": string;
  /** profiles */
  "body.profiles": definitions["profiles"];
  "rowFilter.profiles.slug": string;
  "rowFilter.profiles.title": string;
  "rowFilter.profiles.published_at": string;
  "rowFilter.profiles.created_by": string;
  "rowFilter.profiles.updated_by": string;
  "rowFilter.profiles.created_at": string;
  "rowFilter.profiles.updated_at": string;
  "rowFilter.profiles.id": string;
  /** shows */
  "body.shows": definitions["shows"];
  "rowFilter.shows.slug": string;
  "rowFilter.shows.title": string;
  "rowFilter.shows.state": string;
  /** path or URL to artwork */
  "rowFilter.shows.artwork": string;
  "rowFilter.shows.duration": string;
  "rowFilter.shows.published_at": string;
  "rowFilter.shows.links": string;
  "rowFilter.shows.content": string;
  "rowFilter.shows.tags": string;
  "rowFilter.shows.location": string;
  "rowFilter.shows.id": string;
  "rowFilter.shows.profile": string;
  /** shows_duplicate */
  "body.shows_duplicate": definitions["shows_duplicate"];
  "rowFilter.shows_duplicate.slug": string;
  "rowFilter.shows_duplicate.title": string;
  "rowFilter.shows_duplicate.state": string;
  "rowFilter.shows_duplicate.artwork": string;
  "rowFilter.shows_duplicate.duration": string;
  "rowFilter.shows_duplicate.published_at": string;
  "rowFilter.shows_duplicate.links": string;
  "rowFilter.shows_duplicate.content": string;
  "rowFilter.shows_duplicate.tags": string;
  "rowFilter.shows_duplicate.location": string;
  "rowFilter.shows_duplicate.id": string;
  "rowFilter.shows_duplicate.profile": string;
  /** supply */
  "body.supply": definitions["supply"];
  "rowFilter.supply.id": string;
  "rowFilter.supply.title": string;
  "rowFilter.supply.artwork": string;
  "rowFilter.supply.published_at": string;
  /** tags */
  "body.tags": definitions["tags"];
  "rowFilter.tags.id": string;
  "rowFilter.tags.name": string;
  /** track_links */
  "body.track_links": definitions["track_links"];
  "rowFilter.track_links.id": string;
  "rowFilter.track_links.platform": string;
  "rowFilter.track_links.href": string;
  "rowFilter.track_links.artwork": string;
  "rowFilter.track_links.last_checked_at": string;
  "rowFilter.track_links.track": string;
  /** tracks */
  "body.tracks": definitions["tracks"];
  "rowFilter.tracks.title": string;
  "rowFilter.tracks.slug": string;
  "rowFilter.tracks.path": string;
  "rowFilter.tracks.artwork": string;
  "rowFilter.tracks.artist": string;
  "rowFilter.tracks.id": string;
}

export interface operations {}

export interface external {}
